### ISSUE TITLE
AXU4J 게시판 샘플 관련 질문

### ISSUE THREAD

**Issue by goongdeng** [axisj-com/axu4j#21]
안녕하세요 액시스제이 세미나 갔다와서 프로젝트에 적용을 검토하며, 샘플을 열심 돌리는 중입니다.

의문이 있어 질문드립니다.

axu4j-egovframe의 게시판 샘플을 이용해 적용중인데요

모바일 환경 테스트를 위해, 가로 폭을 줄여보다 발견을 했는데요

버그인지 아니면 어떤 코딩을 더 해야 하는지 잘 모르겠네요

일정 사이즈 이하로 가면, 아래와 같이 안보이는 현상입니다.

그럼, 즐거운 하루 되세요

테스트 환경: IE9, FireFox,
![default](https://cloud.githubusercontent.com/assets/11203496/6436459/0083a8d4-c0f3-11e4-96e1-ed9851c2a052.PNG)

**Comment by hyunjun19** [comment]
지금 FF이랑 IE11에서 문서모드를 9로 놓고 테스트 해봤는데 이상이 없네요.
혹시 브라우저에서 확대/축소 기능을 사용하시거나 윈도우 텍스트 사이즈를 조정하셨나요?

혹시 모르니 다른 PC의 IE에서도 테스트 해보세요.

**Comment by tom-axisj** [comment]
스크립트 구문을 한번 올려주세욤

**Comment by goongdeng** [comment]
다른 브라우저 및 모바일의 브라우저로 접속 시에도 동일한 현상이 발생 합니다.

특별히, 스크립트를 바꾸지는 않았습니다.

아래는 list.jsp 부분 보내드립니다.

**Comment by tom-axisj** [comment]
https://github.com/axisj-com/axu4j/blob/master/axu4j-egovframe/src/main/webapp/WEB-INF/jsp/list.jsp#L170 이부분에 제가 잘못된 코드를 올렸습니다.

```
	                    view: {
	                        label:true,
	                        column: [ // col 은 4
	                            {key:"nttSj", label:"제목", col:4, addClass:"underLine"},
	                            {key:"nttId", label:"번호", col:1},
	                            {key:"desc", label:"비고", col:3},
	                            {key:"frstRegisterNm", label:"작성자"},
	                            {key:"regDate", label:"작성일"},
	                            {key:"", label:"사용자연산", formatter: function(){
	                                return (this.item.no * 987).money();
	                            }}
	                        ],
	                        buttons: [
	                            {addClass:"handle", onclick:function(){
	                                toast.push("handle Click");
	                                trace(this.item);
	                            }}
	                        ]
	                    },
```
이 구문을 제거 해주세요. view 에서 key 값이 잘못 설정 되어 나는 오류 입니다.

**Comment by goongdeng** [comment]
네 잘됩니다. 해결되었습니다.

**Comment by goongdeng** [comment]
감사합니다.^^ :100:

**Comment by tom-axisj** [comment]
아닙니다. 제가 실수를 했습니다. 버그 찾아주셔서 감사합니다.

**Comment by hyunjun19** [comment]
:+1:
