### ISSUE TITLE
이미 만들어진 프로젝트에 AXU4J를 추가 하고 싶을 땐 어떻게 해야 하나요?

### ISSUE THREAD

**Issue by tom-axisj** [axisj-com/axu4j#22]
친절하게 설명해주세요.

**Comment by hyunjun19** [comment]
https://github.com/axisj-com/axu4j/wiki/Manual(ver-0.4.0)#setup 여기에서 setup의 1 ~ 4번을 그대로 따라하시면 됩니다.

어렵지 않아요~
설치도 간단합니다.^^
