### ISSUE TITLE
maven 디버그 모드에서 : source 를 어떻게 하면 찾을 수 있을까요?

### ISSUE THREAD

**Issue by hewon** [axisj-com/axu4j#23]
안녕하세요. 
해당 프로젝트 받아서 해보는데 디버그 모드에서 소스를 못 찾습니다 

## "maven 디버그 모드에서 source를 어떻게하면 찾을 수 있을까요?"

적용해 본 방법은 아래와 같습니다. 
1. tomcat7:run -X

2. 옵션 추가 
   MAVEN_OPTS= -Xdebug -Xnoagent -Xrunjdwp:transport=dt_socket,address=8000,server=y,suspend=n

3. edit lookup source 등록
 
감사합니다.

**Comment by hyunjun19** [comment]
이클립스, 인텔리제이 등등 사용하시는 개발툴을 알려주세요.
개발툴 마다 다를 수 있습니다.

**Comment by hyunjun19** [comment]
만약 이클립스를 사용중이시라면 `edit lookup source 등록` 후 이클립스를 재실행 해보세요.
원래 이클립스는 다시 실행해야 적용되더라구요.

**Comment by hewon** [comment]
이클립스입니다. luna 입니다. 
재부팅해도 안되네요 ^^;;

**Comment by hewon** [comment]
굳이 luna여야 할 이유가 없어 
kepler 로 하니 잘 되네요~
