### ISSUE TITLE
ViewResolver 질문 있습니다. 

### ISSUE THREAD

**Issue by hewon** [axisj-com/axu4j#24]
아래 질문 드렸던 사람입니다. 
다른 질문이 있어 새롭게 글 올립니다. 

-- 질문 발생 
 @RequestMapping(value="/login.do")
 public void loginUsrView() { }

-- 
HTTP Request URI를 변환하여 View 이름 전달하는 것은 아래 클래스라고 이해했습니다. 
"DefaultRequestToViewNameTranslator "

근데 해당 프로젝트에 등록된 viewResolver 는 아래 두개 뿐이더라구요. 
1. BeanNameViewResolver
2. InternalResourceViewResolver

어떻게 return 없이 view 를 알까요?

**Comment by hyunjun19** [comment]
이건 사실 Spring-MVC 규칙인데요.
`return`이 없는 경우 `/login.do` 여기에서 `.do`를 제외한 `login` + `.jsp`를 자동으로 찾습니다.

아래 주소를 보시면 많은 도움이 되실껍니다.
http://javacan.tistory.com/120

**Comment by tom-axisj** [comment]
:+1:

**Comment by InSeoHwang** [comment]
http://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/mvc.html#mvc-ann-return-types

void if the method handles the response itself (by writing the response content directly, declaring an argument of type ServletResponse / HttpServletResponse for that purpose) or if the view name is supposed to be implicitly determined through a RequestToViewNameTranslator (not declaring a response argument in the handler method signature).

좀더 자세한 내용은 RequestToViewNameTranslator 을 찾아보시면 될것같네요~

**Comment by hewon** [comment]
답글 감사합니다. 
알려주신대로 DispatcherServlet 에 들어있네요^^
