### ISSUE TITLE
[AXU4J 게시판]모달 팝업

### ISSUE THREAD

**Issue by goongdeng** [axisj-com/axu4j#27]
일전에 질문드렸는데 오늘은 다른 내용으로 질문 드릴게요

뉴아이패드환경에서  게시판 모달 화면을 테스트하면서 발견한 사항이구요

내용은 모달 팝업을 적용시, 화면을 줄여가면서 테스트 한 결과 모달창이 풀화면으로 띄어지지 않는 현상이 발생합니다.

가로  사이즈(900 > width > 760) 기준의 브라우저 에서  모달팝업시 이미지와 같은 현상이 발생합니다.

물론 다른 영역대에서는 문제가 발생하지 않았습니다.

-----------------------------------------------------------------------
좋은 UI Framework을 만들어주시느라 항상 수고가 많으세요.

그럼, 즐거운 하루되세요
![770](https://cloud.githubusercontent.com/assets/11203496/6610715/b159d06a-c8a6-11e4-81a6-34a675b800bf.PNG)

**Comment by hyunjun19** [comment]
해당문제는 버그가 아니라 설정상 767px 까지 데스크탑으로 간주하게 되어 있어서 그렇습니다.
`list.jsp:266` 라인을 보시면 가로길이 기본값을 900px로 잡았기 때문에 발생하는 문제입니다.

해결 방법은 `list.jsp:266` 라인에서 기본값을 변경하시거나 `list.jsp:256` 라인의 `mediaQuery` 값을 변경하시면 됩니다.

**Comment by goongdeng** [comment]
적용해볼게요 감사합니다
