### ISSUE TITLE
axu4j 지원태그 추가 문의

### ISSUE THREAD

**Issue by tom-axisj** [axisj-com/axu4j#29]
```
<ax:fields> 
<ax:field> 
```

를 지원해주고 있는데요.

```
<ax:table>
<ax:tr>
<ax:td>
```
도 지원해주실 순 없을까요?

**Comment by hyunjun19** [comment]
table tag도 지원할 예정입니다.

**Comment by hyunjun19** [comment]
흠... table 태그 하위 태그들도 생각보다 많은데 전부 지원해야 할지 고민이네요.

`table`, `thead`, `tbody`, `tfoot, `colgroup`, `col`, `tr`, `th`, `td`, `caption`

**Comment by tom-axisj** [comment]
table tr td 만 사용하고 나머지는 자동화하는게 맞는것 같습니다.

**Comment by hyunjun19** [comment]
78f8b5a97edd07978206e3415803f3205f2ce6da
