### ISSUE TITLE
freemaker 버전 개발

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axu4j#6]
freemaker 버전 개발

**Comment by hyunjun19** [comment]
FreemarkerServlet이 taglib를 지원한다고 나와있음.
테스트 필요함

http://freemarker.org/docs/pgui_misc_servlet.html#autoid_56

**Comment by hyunjun19** [comment]
Freemarker + AXU4J 샘플페이지 실행 성공~!

5382c49e4dbe1cd493aafc6deec728323b2ac74c

**Comment by tom-axisj** [comment]
오~ :+1:

**Comment by hyunjun19** [comment]
다행히 Freemarker에서 Custom Tag를 지원해서 설정만 사용 가능하더라구요.
