### ISSUE TITLE
Maven Central Repository Deploy 방법 정리

### ISSUE THREAD

**Issue by hyunjun19** [axisj-com/axu4j#9]
Maven Central Repository Deploy 방법 정리해서 공유하기

**Comment by hyunjun19** [comment]
깃헙 위키? 개인 블로그? 어디에 올리는게 좋을까요?

**Comment by tom-axisj** [comment]
그건 개인블로그가 나으실 것같은데
우리 블로그에도 같이 올려주삼~

**Comment by hyunjun19** [comment]
올릴수 있는데 다 올리죠 머~ ^^;;

**Comment by tom-axisj** [comment]
위키는 설명서를~

**Comment by tom-axisj** [comment]
그리로 깃헙으로 홈피도 만들어 주던데
거기에 위키가 올라가는 것도 같구~

**Comment by tom-axisj** [comment]
셋팅에 > GitHub Pages 하면 axu4j.github.com 으로 웹사이트 생성

**Comment by hyunjun19** [comment]
0.2.0-RELEASE 설명서 만들기 #10

**Comment by hyunjun19** [comment]
http://axisj-com.github.io/axu4j/ 생성되었네요.

**Comment by tom-axisj** [comment]
점 멋진듯~

**Comment by hyunjun19** [comment]
http://westzero.tistory.com/117
http://blog.axisj.com/archives/309

포스팅 완료~!
4일이나 삽질했는데 정리하니 얼마 안되네요. ㅜㅜ
